- name: deployment playbook
  hosts: node0
  become: true
  remote_user: pi
  tasks:
    - name: Test connection
      ping:
    - name: Create base installation directory if does not exists
      file:
        path: /usr/pi-as-server
        state: directory
        mode: '0755'
    - name: Create application base directory if does not exists
      file:
        path: /usr/pi-as-server/student-service
        state: directory
        mode: '0755'
    - name: Find out playbooks path
      shell: pwd
      register: playbook_path_output
    - debug: var=playbook_path_output.stdout
    - name: Copy application jar
      copy:
        src: /var/lib/jenkins/workspace/student-service_master/app/build/lib/api*.jar
        dest: /usr/pi-as-server/student-service/
        delegate_to: node0