- name: deployment playbook
  hosts: node0
  become: true
  remote_user: pi
  tasks:
    - name: Test connection
      ping:
    - name: Create base installation directory if does not exists
      file:
        path: /usr/pi-as-server
        state: directory
        mode: '0755'
    - name: Create application base directory if does not exists
      file:
        path: /usr/pi-as-server/student-service
        state: directory
        mode: '0755'
