---
- name: Test connection
  ping:
- name: Create base installation directory if does not exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/usr/pi-as-server"
    - "/usr/pi-as-server/student-service/"
    - "/usr/pi-as-server/student-service/config"
- name: Copying configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "config/", dest: "/usr/pi-as-server/student-service/config/" }
- name: Copying application JAR file
  copy:
    src: "{{ item }}"
    dest: "/usr/pi-as-server/student-service/student-service.jar"
  with_fileglob:
    - app*
- name: Start Student-service application
  shell: 'sh start.sh'