---
- name: Test connection
  ping:
- name: Create base installation directory if does not exists
  file:
    path: /usr/pi-as-server
    state: directory
    mode: '777'
- name: Create application base directory if does not exists
  file:
    path: /usr/pi-as-server/student-service
    state: directory
    mode: '777'
- name: Copying configuration files
  copy:
    src: "a/a/a/kapplication.yaml"
    dest: "/usr/pi-as-server/student-service"
    mode: '777'
    remote_src: yes
  debugger: on_failed